### ISSUE TITLE
Scale Dot-Product Attentionの作成

### ISSUE THREAD

**Issue by yukihito-jokyu** [yukihito-jokyu/transformers_scratch#10]
[参考サイト](https://www.nomuyu.com/multi-head-attention/#st-toc-h-2)からScale Dot-Product Attentionの作成方法を考える。

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by yukihito-jokyu** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

What is it?

**Comment by yukihito-jokyu** [comment]
[数式](https://github.com/yukihito-jokyu/transformers_scratch/issues/5#issuecomment-2330552312)

**Comment by yukihito-jokyu** [comment]
入力
[batch_size, sequence_size, d_model]

重みの次元数はhead=1の時(d_model × d_model)

ハイパーパラメータは縦と横の次元数

**Comment by yukihito-jokyu** [comment]
Multi-Head Attention内に線形変換できる重みWq,Wk,Wvを置いておく。その後のattentionでheadごとに分割する。

**Comment by yukihito-jokyu** [comment]
引数はd_model(次元数)とhead数

**Comment by yukihito-jokyu** [comment]
作成したのでいったん閉じる
